### ISSUE TITLE
consider making the computed properties `readOnly`

### ISSUE THREAD

**Issue by stefanpenner** [kaliber5/ember-responsive-image#1]
Just skimmed the add-on, and noticed many computed properties. Most (or all) don't make sense to be changed independent of the dependent keys they declare changing. (lets say via `.set` or some other accidental way).

It may be a matter of taste, but having debug many related heisenbugs I generally recommend  computed properties to be marked as `readOnly` unless ofcourse they explicit support the `set` case (which in practice is rare).

The easiest way to do this, is as follows:
```js
propertyName: computed('x','y', function() { /* ... code ... */ }).readOnly()
```

If you don't think this matters, feel free to disregard this issue. Anyways, cool add-on!

**Comment by andreasschacht** [comment]
Thanks for the hint. I agree. I've changed the mode to readonly in the manner you suggested.

**Comment by simonihmig** [comment]
And I thought this was a little self-promotion for [ember-improved-cp](https://github.com/stefanpenner/ember-improved-cp)? ;)

No, seriously, this is certainly a valid concern. @andreasschacht 👍 for the quick fix. We should probably look out for this in our other code bases as well...
