### ISSUE TITLE
Using the screen width rather than the viewport width results in too-large images

### ISSUE THREAD

**Issue by nathanielw** [kaliber5/ember-responsive-image#11]
Hi, thanks for the addon, it's very useful :)

I might have missed there being some reason for this, but using the screen width as the base for picking the image size (in [`getDestinationWidthBySize()`](https://github.com/kaliber5/ember-responsive-image/blob/6b1648527074f88a17e194c79afaec48ab32d7d3/addon/services/responsive-image.js#L84)) seems incorrect. On desktop, the screen size isn't necessarily the same as the browser viewport size (since the browser can be resized), which means the helpers, components, etc. that get the "best fitting" image over-estimate the on-page size of the image if the browser isn't fullscreen.

I think it'd make more sense to use `$(window).width()` (or `document.documentElement.clientWidth`).

**Comment by andreasschacht** [comment]
Hi Nathaniel,
thanks for your hint. After some discussion we pointed out, that the 'correct' width is a matter of opinion. From our point of view it make sense to load the image with `screen.width`, so after resizing the Browser to fullscreen, the image still have the fitting size and it's not necessary to scale up or load the image with a new size.
But that's just our opinion, so we decided to make the `screenWidth`-property of the ResponsiveImageService public. The calculation based on this value and it's default is still the `screen.width`. 
Now you can extend the Service and/or set a new value to this property, so it'll fit your needs!
