### ISSUE TITLE
Support LQIP technique

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-responsive-image#13]
Some background: https://jmperezperez.com/medium-image-progressive-loading-placeholder/

As we control the image generation at build time as well as the markup, we are in a good position to support something like this with zero effort for the user. Especially rendering the image with a really low-res image that is added inline with a [Data URI](https://en.wikipedia.org/wiki/Data_URI_scheme) should be a nice solution, as no additional request is needed.

This idea needs to be fleshed out a bit more though, like downsides of inlining (increases JS payload for every image) vs. additional request etc.

**Comment by simonihmig** [comment]
Somewhat related: https://github.com/DockYard/ember-skeleton

**Comment by andreasschacht** [comment]
closed in #38
