### ISSUE TITLE
Should we change/rename the component API?

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-responsive-image#141]
Currently the basic invocation of the component looks like `<ResponsiveImage @image="some/image.jpg"/>`, and that does not change so far in the upcoming v2.

However as there are *so many*  breaking changes (not really hard to fix, but just a bunch of them), we have the opportunity now to add more breaking changes, if we think they are justified.

My current thinking goes towards aligning the API more to match what a plain image tag would look like:

```hbs
<Image @src="some/image.jpg"/>

vs.

<img src="some/image.jpg"/>
```

Maybe using `Image` as the component name could lead to conflicts with other components of user's apps though? Unless we get template imports, component names are still global and static, so that could be bad? (There is still an escape hatch by re-exporting the component in the app under a different name/module though!)

Maybe just rename `@image` to `@src`, therefore? I.e. `<ResponsiveImage @src="some/image.jpg"/>`

Or keep everything as it is now? 🤔

@andreasschacht @lolmaus thoughts?

**Comment by lolmaus** [comment]
`@src` is too similar to the `src` HTML attr. Some devs might assume that it requires a domain root-relative path, as opposed to a source dir-relative path.

**Comment by simonihmig** [comment]
> Some devs might assume that it requires a domain root-relative path, as opposed to a source dir-relative path.

It *does* now require a root-relative path! 😆

That's part of some breaking changes to the configuration, as you can now have basically a glob that specifies the images to be scaled. So there is no thing as a "sourceDir" anymore. And also no ambiguity between different images with same names in different folders.

So that's why I was thinking to make it resemble more the native `src`. As when you have some basic `<img src="image.jpg"/>` in your app and want to introduce e-r-i, you just have to change the tag name to the component name, and make `src` an argument `@src`...

**Comment by lolmaus** [comment]
Okay, let's go for it then!

But please add either an `UPGRADING.md` or an `Upgrading` section to `README.md`.

**Comment by simonihmig** [comment]
#154 renamed argument to `@src`, keeping component name the same.
