### ISSUE TITLE
Copying of images is pretty slow

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-responsive-image#22]
```
160 images copied


Build successful - 97020ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
ImageResizer                                  | 93814ms             
```

The `copyImages` method extracts the image meta data for each supported width, although that is always the same (for a given file). Probably moving this gm-stuff (https://github.com/kaliber5/ember-responsive-image/blob/master/broccoli-image-writer.js#L99-L105) out of the `forEach` loop can help to speed things up!

**Comment by andreasschacht** [comment]
#23 will speedup image generation
