### ISSUE TITLE
[Feature request] Make it possible to export the image meta data as JSON files

### ISSUE THREAD

**Issue by Windvis** [kaliber5/ember-responsive-image#227]
I'm creating a portfolio website which has multiple pages with a lot of images each. It would be nice if I could configure this addon in some way that it outputs JSON files with the image meta data instead of embedding it all in the index.html.

That way I could manually fetch these files and add the data to the service on demand. Combined with FastBoot's Shoebox this would allow me to only include the minimum amount of meta data in the HTML body.

Do you think something like this would be a good addition or is it a niche use case?

**Comment by simonihmig** [comment]
It looks like a rather niche use case, but still not uninteresting. I did some major refactoring of the JSON metadata before the 2.0 release to keep the size small, as it was growing way too much when the additional image formats have been introduced.

However I am not sure how this could work. Like how would the addon know how to split this up? Would the user have to configure this, i.e. specify the boundaries of which images go into which "chunk"?

Mind though that you would have to have the json loaded before rendering the new route, which delays the rendering and provides a new possible point of failure. So not sure if that will lead to increasing or actually decreasing performance!?

About how many images are we talking here?
