### ISSUE TITLE
Allow fingerprinting of generated images

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-responsive-image#3]
This addon allows resolving the fingerprinted asset path, even when generating the path dynamically: https://github.com/RuslanZavacky/ember-cli-ifa. This could solve the current problem having to turn off fingerprinting for our generated images.

We could either add ifa as a dependency to this addon so it is always available. Or dynamically detect its presence and add support for it when available.

**Comment by andreasschacht** [comment]
v0.5.0 now supports fingerprinted images :-)

**Comment by simonihmig** [comment]
👍🍾👏🚀
