### ISSUE TITLE
[Windows] imageName lookup fails due to filepath inconsistencies

### ISSUE THREAD

**Issue by elwayman02** [kaliber5/ember-responsive-image#337]
On a windows machine, the metadata object of images uses backslashes and forward slashes inconsistently, since one path comes from the browser and the other comes from Windows itself. This causes the key lookup to fail here:

https://github.com/kaliber5/ember-responsive-image/blob/master/addon/services/responsive-image-local.ts#L52

![image](https://user-images.githubusercontent.com/1325482/132394986-550f1f49-3767-45a0-a88d-d5bbb0ca1e1c.png)

The likely fix is to add a case to the `normalizeImageName` method here: https://github.com/kaliber5/ember-responsive-image/blob/f72157adabe0e055e750bd5167882c77bf78d707/addon/services/responsive-image-local.ts#L58

**Comment by simonihmig** [comment]
Was able to reproduce in CI when adding Windows: #338
