### ISSUE TITLE
Incorrect image paths on Windows

### ISSUE THREAD

**Issue by scathers** [kaliber5/ember-responsive-image#34]
When I build on Windows, I get broken paths to the images, because the paths have backslashes (presumably because this is the Windows file separator) rather than the forward slashes that are required in URLs. I was able to fix this by replacing the backslashes with forward slashes using a regex like this:
`let correctImagePath = originalImagePath.replace(/\\/g, '/');`

I believe if this was done with `image` variable in the line linked below, it would fix the problem. There may also be a better solution using a `path.posix` method rather than `path.join` (because `path.join` uses the system separator rather than always using a forward slash).

https://github.com/kaliber5/ember-responsive-image/blob/7108fe95571296f35d7515a8577dacbd9f4debe3/broccoli-image-writer.js#L129

**Comment by simonihmig** [comment]
@scathers Thanks for reporting! Seems you are right, `path.join` should be used only for file paths, not URLs... will try to fix this asap!
