### ISSUE TITLE
Add support for background images

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-responsive-image#4]
We will need this for TLW sooner than later! :)

Could be a helper for simple elements and a mixin for components. Logic similar to that of the current implementation of the `src` attribute.

Probably makes sense to refactor things a bit, i.e. add a service that contains all the pieces (like the `supportedWidths`) that the component, helper and mixin can use.

**Comment by andreasschacht** [comment]
The new version provides now components, mixins, a helper and a service.
