### ISSUE TITLE
Allow file paths as sourceDir

### ISSUE THREAD

**Issue by jasonmevans** [kaliber5/ember-responsive-image#54]
It would be very useful to be able to assign a file path to the `sourceDir` configuration. With the current configuration, you are forced to organize your resources in a way that is amenable to defining the configurations per folder, which can make things a little messy. 

For instance, on our homepage, we have a hero image that needs to be resized with a specific set of dimensions. There is also a background image on that page that needs a different set of dimensions. We wish to keep these two images in the same assets folder, but process them differently. In order to achieve this with the current `ember-responsive-image` we must place each image in a folder by itself so that we can define separate configurations. 

This has a slight orthogonal relationship to https://github.com/kaliber5/ember-responsive-image/issues/50

**Comment by simonihmig** [comment]
Closed by #115
