### ISSUE TITLE
Support ...attributes

### ISSUE THREAD

**Issue by NullVoxPopuli** [kaliber5/ember-responsive-image#56]
I was thinking about implementing: https://github.com/ember-learn/ember-website/issues/184

but immediately ran in to an issue where not all attributes are forwarded to the rendered element. :-\

**Comment by simonihmig** [comment]
How exactly is this not working? The code base is admittedly quite out-dated, but as the component is still a classic `Ember.Component` with a `tagName: 'img'`, any angle bracket invocation with attributes should still add those to that default `<img>` element!? 🤔

**Comment by NullVoxPopuli** [comment]
I wish I had included more details in the original post :(
