### ISSUE TITLE
Support WebP

### ISSUE THREAD

**Issue by NullVoxPopuli** [kaliber5/ember-responsive-image#57]
When starting to try to work on: https://github.com/ember-learn/ember-website/issues/184

Wanted to try WebP for the image format for responsiveness, because by the team the above issue is resolved, WebP will probably be available in all browsers.

**Comment by simonihmig** [comment]
Not sure what you have in mind for SVG support? As it's a vector graphic format and thus perfectly scalable to all resolutions, why would you want generate differently "sized" versions (whatever that means for SVG), which this addon is all about?

**Comment by NullVoxPopuli** [comment]
that's a good point. I misunderstood the core of the issue on the ember-website
