### ISSUE TITLE
Support rootUrl where baseUrl is missing

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-responsive-image#6]
The `baseUrl` config option is deprecated, see http://emberjs.com/blog/2016/04/28/baseURL.html
When it is not available, it should use `rootUrl` here: https://github.com/kaliber5/ember-responsive-image/blob/master/addon/services/responsive-image.js#L124

**Comment by andreasschacht** [comment]
Added rootUrl as fallback
