### ISSUE TITLE
LQIP

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-responsive-image#90]
https://www.industrialempathy.com/posts/image-optimizations/#blurry-placeholder

With native lazy loading (#89), do we still need the addon-addons (https://github.com/kaliber5/ember-lazy-responsive-image + https://github.com/kaliber5/ember-cli-lazysizes), or should we simply apply the blurry placeholder within this addon? (by default or opt-in)

Related:
* https://github.com/google/eleventy-high-performance-blog/blob/main/_11ty/blurry-placeholder.js

**Comment by nickschot** [comment]
Would imo be great to have a single addon that covers this (native lazy loading + opt-in blurry placeholder).
